# Application
quarkus.application.name=delivery-service
quarkus.http.port=8084

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=delivery
quarkus.datasource.password=delivery
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5444/deliverydb

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Delivery Service API
quarkus.smallrye-openapi.info-version=1.0.0
