# VERSION 7 — OpenAPI + Health
quarkus.http.port=8080

app.name=TaskManager
app.version=8.0
app.welcome-message=TaskManager avec OpenAPI et Health Checks
app.pagination.default-size=10
app.pagination.max-size=50

# Dev Services PostgreSQL
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.sql-load-script=import.sql

# Test : H2 en mémoire
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.hibernate-orm.database.generation=drop-and-create

# Prod
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:taskdb}
%prod.quarkus.datasource.username=${DB_USER:task}
%prod.quarkus.datasource.password=${DB_PASS:task}
%prod.quarkus.hibernate-orm.database.generation=update

# ✨ NOUVEAU : OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=TaskManager API
quarkus.smallrye-openapi.info-version=7.0
quarkus.smallrye-openapi.info-description=API de gestion de tâches — Formation Quarkus
quarkus.swagger-ui.always-include=true

# ✨ NOUVEAU : Health endpoints exposés
quarkus.health.extensions.enabled=true
