# Application
quarkus.application.name=restaurant-service
quarkus.http.port=8082

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=restaurant
quarkus.datasource.password=restaurant
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5442/restaurantdb

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Restaurant Service API
quarkus.smallrye-openapi.info-version=1.0.0
