# Application
quarkus.application.name=customer-service
quarkus.http.port=8081
quarkus.http.host=0.0.0.0
# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=customer
quarkus.datasource.password=customer
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5441/customerdb

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Customer Service API
quarkus.smallrye-openapi.info-version=1.0.0
