# Application
quarkus.application.name=order-service
quarkus.http.port=8083

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=orderuser
quarkus.datasource.password=orderpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5443/orderdb

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# REST Clients
quarkus.rest-client.customer-api.url=http://localhost:8081
quarkus.rest-client.customer-api.scope=jakarta.inject.Singleton
quarkus.rest-client.restaurant-api.url=http://localhost:8082
quarkus.rest-client.restaurant-api.scope=jakarta.inject.Singleton
quarkus.rest-client.delivery-api.url=http://localhost:8084
quarkus.rest-client.delivery-api.scope=jakarta.inject.Singleton

# Timeouts
quarkus.rest-client.customer-api.connect-timeout=3000
quarkus.rest-client.customer-api.read-timeout=5000
quarkus.rest-client.restaurant-api.connect-timeout=3000
quarkus.rest-client.restaurant-api.read-timeout=5000
quarkus.rest-client.delivery-api.connect-timeout=3000
quarkus.rest-client.delivery-api.read-timeout=5000

# Order config
foodexpress.order.minimum-amount=10.00
foodexpress.order.max-delivery-radius-km=15

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Order Service API
quarkus.smallrye-openapi.info-version=1.0.0
